pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                sh './gradlew assemble' // TODO: This builds the project
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                sh './gradlew test' // TODO: This runs tests
            }
        }
    }
}
